{"uuid": "762b1d13-9d24-4b74-8da6-f9e85a12d7c6", "children": ["9863867b-a4dc-4a91-a7d2-e1ca6d122546", "c7651fc6-c943-4e83-91b4-45448db24cac", "d640ad0b-80b0-4aa7-83af-47bcb2709404", "edea2aba-5863-46d8-9c10-93ac6bb28deb"], "befores": [{"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_data_count.py\", line 31, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【数据列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_data_count.py\", line 31, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031297968, "stop": 1754031297968}], "start": 1754031297968, "stop": 1754031297979}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_data_count.py\", line 31, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【数据列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_data_count.py\", line 31, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031298997, "stop": 1754031298997}], "start": 1754031298995, "stop": 1754031298997}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_data_count.py\", line 31, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【数据列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_data_count.py\", line 31, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031300015, "stop": 1754031300015}], "start": 1754031300015, "stop": 1754031300016}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_data_count.py\", line 31, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【数据列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_data_count.py\", line 31, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031301034, "stop": 1754031301034}], "start": 1754031301034, "stop": 1754031301035}], "start": 1754031301034, "stop": 1754031301048}