{"uuid": "09b8ca61-f1b7-4739-bbc8-53e3051bdd5d", "children": ["f5028bff-8ed0-4390-97ff-97ae6b6563f0"], "befores": [{"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_file_count.py\", line 33, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【文件列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_asset_discovery\\test_file_count.py\", line 33, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\pythonProject3\\autotest_api\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1753963418469, "stop": 1753963418469}], "start": 1753963418468, "stop": 1753963418472}], "start": 1753963418468, "stop": 1753963418497}