{"uuid": "0e932eb1-f5fc-49b2-9604-ed6de9a9b615", "children": ["453622e2-3946-4c89-81ee-cc15d9ee04f2", "3e418e71-b2ad-4ee4-b229-466350e2cf67", "c7598034-db99-4eb8-ae78-af5dbbaa6713", "996d858c-f586-4ba3-8e45-c88a4666f3fd"], "befores": [{"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_risk_overview\\test_data_assets.py\", line 32, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【数据列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_risk_overview\\test_data_assets.py\", line 32, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031294583, "stop": 1754031294583}], "start": 1754031294582, "stop": 1754031294602}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_risk_overview\\test_data_assets.py\", line 32, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【数据列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_risk_overview\\test_data_assets.py\", line 32, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031295910, "stop": 1754031295910}], "start": 1754031295909, "stop": 1754031295911}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_risk_overview\\test_data_assets.py\", line 32, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【数据列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_risk_overview\\test_data_assets.py\", line 32, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031296928, "stop": 1754031296928}], "start": 1754031296928, "stop": 1754031296929}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_risk_overview\\test_data_assets.py\", line 32, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【资产】-【数据列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_risk_overview\\test_data_assets.py\", line 32, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031297949, "stop": 1754031297949}], "start": 1754031297948, "stop": 1754031297949}], "start": 1754031297948, "stop": 1754031297962}