{"uuid": "2db5b8c7-bfb1-47be-a6a1-806a98d79046", "children": ["a21483cc-d366-4592-8b4f-596525da141e", "3a7c106d-bd19-469c-93b8-2302f7ebf6d1", "b9e61f35-ff7f-4d7b-a8f1-277c9dd728ce", "798f14f1-bc84-4f5a-827f-04bf38829fda"], "befores": [{"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_pending_vul_event\\test_vul_high.py\", line 30, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【弱点】-【弱点事件列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_pending_vul_event\\test_vul_high.py\", line 30, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031294582, "stop": 1754031294583}], "start": 1754031294582, "stop": 1754031294600}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_pending_vul_event\\test_vul_high.py\", line 30, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【弱点】-【弱点事件列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_pending_vul_event\\test_vul_high.py\", line 30, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031295909, "stop": 1754031295909}], "start": 1754031295909, "stop": 1754031295909}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_pending_vul_event\\test_vul_high.py\", line 30, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【弱点】-【弱点事件列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_pending_vul_event\\test_vul_high.py\", line 30, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031296928, "stop": 1754031296928}], "start": 1754031296928, "stop": 1754031296929}, {"name": "_xunit_setup_class_fixture_TestCase", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 792, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\python.py\", line 720, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_pending_vul_event\\test_vul_high.py\", line 30, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "【弱点】-【弱点事件列表】接口", "status": "failed", "statusDetails": {"message": "Failed: setup_class: 未获取到 token\n", "trace": "  File \"D:\\pythonProject3\\autotest_api\\test_case\\test_pending_vul_event\\test_vul_high.py\", line 30, in setup_class\n    pytest.fail(\"setup_class: 未获取到 token\")\n  File \"D:\\my_venv\\myenv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1754031297946, "stop": 1754031297947}], "start": 1754031297946, "stop": 1754031297948}], "start": 1754031297946, "stop": 1754031297959}